# Generated by Django 4.1.5 on 2023-01-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_assestment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assestment',
            name='id',
        ),
        migrations.AlterField(
            model_name='assestment',
            name='user_id',
            field=models.TextField(primary_key=True, serialize=False, unique=True),
        ),
    ]
