# Generated by Django 4.1.5 on 2023-01-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_assestment_id_alter_assestment_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='assestment',
            name='gender',
            field=models.CharField(default='Male', max_length=6),
        ),
    ]
