# Generated by Django 4.1.5 on 2023-01-15 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_job_description_assestment_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='tier_one_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='tier_three_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plans',
            name='tier_two_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
